### ISSUE TITLE
Renommer le dépôt en "bal_validator"

### ISSUE THREAD

**Issue by MaelREBOUX** [etalab/outils-bal#8]
Ca serait mieux pour la visibilité / lisibilité du dépôt. Les BAL ce sont les fichiers de données.

**Comment by jdesboeufs** [comment]
`validateur-bal` ?

**Comment by jdesboeufs** [comment]
En fait j'avais imaginé qu'on pourrait avoir d'autres commandes que `validate`.

**Comment by jdesboeufs** [comment]
Mais on peut faire quelque chose du genre `bal-tools` ou `outils-bal`

**Comment by MaelREBOUX** [comment]
Va pour "outils-bal" alors

**Comment by jdesboeufs** [comment]
Done.
